#!/bin/bash

set -e
set -u
set -o pipefail

script_dir=$(dirname "$(realpath "$0")")
root_dir="$script_dir/.."
bootstrap_dir="$root_dir/out/bootstrap"
src_dir="$bootstrap_dir/src"
build_dir="$bootstrap_dir/build"
repo_url="${COG_REPO:-file://$root_dir}"

prev_stage=

section() {
    echo
    echo "==> $1"
    echo
}

checkout() {
    local commit
    if git rev-parse --quiet --verify "$1" >/dev/null; then
        commit="$1"
    else
        pattern="^$(sed 's/[$\.*[\^]/\\&/g' <<<"$1")$"
        commit="$(git rev-list master --grep "$pattern" --max-count=1)"
        if [[ -z "$commit" ]]; then
            echo "Commit not found: $1"
            exit 1
        fi
    fi

    echo "Checking out \"$(git log --format="%h %s" -n 1 "$commit")\""
    git checkout --quiet "$commit"
}

stage() {
    local i="$1"
    local ref="$2"

    section "Building stage $i"

    local stage_dir="$build_dir/stage$i/"
    mkdir -p "$stage_dir"

    checkout "$ref"

    local cogc=""
    if [ -n "$prev_stage" ]; then
        cogc=$(realpath "$build_dir/$prev_stage/cogc")
    fi

    make -C compiler "BUILD_DIR=$stage_dir" "COGC=$cogc"

    prev_stage="stage$i"
}

verify() {
    section "Verifying final stage"

    mkdir -p "$build_dir/verify"

    make -C compiler "BUILD_DIR=$build_dir/verify" "COGC=$(realpath "$build_dir/$prev_stage/cogc")"

    echo "Comparing executables"

    objdump -dr -j .rodata -j .text "$build_dir/$prev_stage/cogc" | tail -n +3 >"$build_dir/verify/cogc.objdump"
    objdump -dr -j .rodata -j .text "$build_dir/verify/cogc" | tail -n +3 >"$build_dir/verify/cogc.verify.objdump"
    diff "$build_dir/verify/cogc.objdump" "$build_dir/verify/cogc.verify.objdump" && echo "No difference" || echo "^^^ Difference found"
}

rm -rf "$bootstrap_dir"
mkdir -p "$bootstrap_dir" "$src_dir" "$build_dir"
cd "$src_dir"

git clone --quiet --filter=tree:0 "$repo_url" .

stage 0 "Make compilation of bootstrap compiler stricter"

stage 1 "Replace bootstrap compiler with self-host compiler"

stage 2 "feat: Add support for include files"

stage 3 "feat(compiler): Add never type"

stage 4 "Merge branch 'compiler-rewrite'"

stage 5 "feat(compiler): Add for loops"

stage 6 "feat(compiler): Add struct initializer expressions"

stage 7 "feat(compiler): Add struct inheritance"

stage 8 "feat(compiler): Add struct inheritance"

verify

mkdir -p "$bootstrap_dir/bin"

cp "$build_dir/$prev_stage/cogc" "$bootstrap_dir/bin/cogc"

section "Done"
